### ISSUE TITLE
Problema al ingresar Led1 en bloque Establecer gpio en 

### ISSUE THREAD

**Issue by epernia** [leandrolanzieri/ciaabot-ide#17]
No deja Elehir Led1 en el combo.

**Comment by leandrolanzieri** [comment]
Se debía a que la primera opción de las listas largas quedan solapadas por la zona 'drag' de la ventana. 

**Este fix se incluirá en la siguiente versión:**
![image](https://user-images.githubusercontent.com/5381296/29496167-84947154-85a3-11e7-8749-b1ba05802fb9.png)
